### ISSUE TITLE
Access application via web UI

### ISSUE THREAD

**Issue by ayashkov** [granito-source/segovia#1]
As a _Student_ I want to be able to access the application via web interface, so that I could study using any modern web browser.

### Acceptance criteria

Confirm that:

* the application JAR can be started successfully from the command line;
* the application keeps running until it receives `SIGINT`;
* the application listens on port `8080`;
* accessing <http://localhost:8080/> shows a web page with _Segovia_ title and _Segovia_ headline.

### Tasks

- [x] Create Gradle project.
- [x] Setup CI integration.
- [x] Create Angular placeholder (`ui` module).
- [x] Create web application (`web` module).
- [x] Create application executable JAR (`app` module) with Concordion integration tests.
