### ISSUE TITLE
Show sentence

### ISSUE THREAD

**Issue by ayashkov** [granito-source/segovia#2]
As a _Student_ I want to see one sentence in the foreign language to work on, so that I could learn the language by answering challenges about the sentence.

### Acceptance criteria

Confirm that:

* when a user accesses **/study** page, it shows the sentence stored in the backend rendered on the page.

### Assumptions

* Until we have various languages and students' profiles showing what language they know and what they study, the native language is English and the foreign language is Spanish. We can start with this pair: [Mala Hierba](https://www.gutenberg.org/cache/epub/43017/pg43017-images.html) and [Weeds](https://www.gutenberg.org/cache/epub/61183/pg61183-images.html).
* This story deals with just one sentence, but we want this to be a tracer bullet story, showing that SPA can talk to the backend API. How the backend persists the sentence is not important at this time.
* Persistence is not in scope now: any fake repository will do.

### Tasks

- [x] Update software specifications.
- [x] Create the root web entry point.
- [x] Create a web entry point for sentences: list, fetch.
- [x] Create a use case to list available sentences (just one for now).
- [x] Create a use case to fetch a sentence by its ID.
- [x] Create UI component to render a sentence from API.
- [x] Create UI service to get get sentences.
- [x] Create UI service to get the API root.
