### ISSUE TITLE
Show sentence translation

### ISSUE THREAD

**Issue by ayashkov** [granito-source/segovia#4]
As a _Student_ I want to see on demand the translation for the sentence I work on, so that I could understand the meaning of it.

### Acceptance criteria

Confirm that:

* a displayed sentence is clickable when its translation exists and not clickable otherwise;
* when clicked, a pop-up window with the translation of the sentence is shown;
* when the pop-up is shown, clicking anywhere outside of its area closes the pop-up.

### Assumptions

* Foreign language is Spanish (`es`).
* Native language is English (`en`).

### Tasks

- [ ] Update the specification.
- [x] Add language code to the URI.
- [ ] Add optional `translation` link to `Sentence` resource.
- [ ] Add Angular Material.
- [ ] Update UI to make the link clickable when translation is available.
- [ ] Update UI to show a pop-up with translation.
- [ ] Publish specification.

### See also

* [ISO 639 language codes](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes)
* Story #2.
* Story #5.
